# Generated by Django 5.0.7 on 2024-08-16 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.IntegerField()),
                ('midia_type', models.CharField(default=None, max_length=10)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_de_midias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'media_id', 'midia_type')},
            },
        ),
    ]
